spring:
    pulsar:
      client:
#        service-url: pulsar+ssl://sn-academy.sndevadvocate.snio.cloud:6651
        service-url: pulsar://pulsar1:6650
#        auth-plugin-class-name: org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2
#        auth-params: "{\"privateKey\":\"file:///Users/tspann/Downloads/sndevadvocate-tspann.json\",\"issuerUrl\":\"https://auth.streamnative.cloud/\", \"audience\":\"urn:sn:pulsar:sndevadvocate:my-instance\"}"
      producer:
        batching-enabled: false
        send-timeout-ms: 90000
        producer-name: airqualityjava
        topic-name: persistent://public/default/airquality

airnowapi:
  base-url: https://www.airnowapi.org
  airquality-uri: /aq/observation/zipCode/current/?format=application/json&distance=250&zipCode={zipCode}&API_KEY={apiKey}
  api-key: ${API_KEY:}
  zip-codes:
    - 08520
    - 94027
    - 02199
    - 11962
    - 94957
    - 90402
    - 94301
    - 07070
    - 90265
    - 90272
    - 10013
    - 10007
    - 94123
    - 77449
    - 11368
    - 60629
    - 79936
    - 75034
    - 94016
    - 79936

logging:
  level:
    org.apache.pulsar: error
    root: info
    ROOT: info
    dev.datainmotion.airquality: debug

server.port: 8999